apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: prasanna1908/payment-service:latest   # Replace with your Docker image
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server.default.svc.cluster.local:8761/eureka"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.default.svc.cluster.local:9092"
            - name: POSTGRES_DB_URL
              value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/paymentDB"
            - name: API_GATEWAY_URL
              value: "http://api-gateway.default.svc.cluster.local:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
