apiVersion: apps/v1
kind: Deployment
metadata:
  name: axon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axon-server
  template:
    metadata:
      labels:
        app: axon-server
    spec:
      containers:
        - name: axon-server
          image: axoniq/axonserver:latest
          ports:
            - containerPort: 8124
---
apiVersion: v1
kind: Service
metadata:
  name: axon-server
spec:
  type: NodePort  # Expose the service via a NodePort
  ports:
    - port: 8124
      targetPort: 8124
      protocol: TCP
      name: http
      nodePort: 30001  # External port you can use to access the service
  selector:
    app: axon-server
