apiVersion: apps/v1
kind: Deployment
metadata:
  name: axon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axon-server
  template:
    metadata:
      labels:
        app: axon-server
    spec:
      containers:
        - name: axon-server
          image: axoniq/axonserver:latest
          ports:
            - containerPort: 8024
            - containerPort: 8124
---
apiVersion: v1
kind: Service
metadata:
  name: axon-server
spec:
  selector:
    app: axon-server
  ports:
  - name: http
    protocol: TCP
    port: 8024
    targetPort: 8024
  - name: grpc
    protocol: TCP
    port: 8124
    targetPort: 8124
  type: LoadBalancer
