apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: steeltoeoss/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: eureka.client.register-with-eureka
              value: "false"
            - name: eureka.client.fetch-registry
              value: "false"
            - name: eureka.server.enable-self-preservation
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
