apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-db
          image: busybox
          command: ["/bin/sh", "-c", "bash /docker-entrypoint-initdb.d/init-db.sh"]
          volumeMounts:
            - name: init-db-scripts
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Prasanna@123"
          ports:
            - containerPort: 5432
      volumes:
        - name: init-db-scripts
          configMap:
            name: init-db-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
